# Python Fundamentals Practice Notebook

## Week 2: Master the Basics of Python

This notebook guides you through fundamental Python concepts. Run each cell and complete the exercises.

---

In [1]:
print("My environment is called intern")

My environment is called intern

In [1]:
A="Variable A"
print(A)
type(A)

Variable A

str

## 1. Data Types

Python has several built-in data types. Let's explore them:
- **int**: Integer numbers (e.g., 5, -3, 0)
- **float**: Decimal numbers (e.g., 3.14, -0.5)
- **str**: Text (e.g., "Hello", 'World')
- **bool**: True or False
- **list**: Ordered collection [1, 2, 3]
- **dict**: Key-value pairs {"name": "John"}

In [18]:
# Example: Creating variables of different types
age = 25              # int
height = 5.11          # float
name = "Victor"        # str
is_student = True     # bool

print(f"My name is {name}")
print(f"I am {age} years old")
print(f"My height is {height} feet")
print(f"Am I a student? {is_student}")

# Check the type of a variable
print(f"\nType of age: {type(age)}")
print(f"Type of height: {type(height)}")
print(f"Type of name: {type(name)}")

My name is Victor
I am 25 years old
My height is 5.11 feet
Am I a student? True

Type of age: <class 'int'>
Type of height: <class 'float'>
Type of name: <class 'str'>

In [19]:
print(f"My height is {height} feet")

My height is 5.11 feet

### Exercise 1.1: Create Your Profile
Fill in the variables below with your information:

In [ ]:
# TODO: Fill in your information
my_name = ""  # Your name here
my_age = 0      # Your age here
my_hobby = ""  # A hobby you enjoy
years_coding = 0  # How many years have you coded?

# Print your profile
print(f"Name: {my_name}")
print(f"Age: {my_age}")
print(f"Hobby: {my_hobby}")
print(f"Years of coding experience: {years_coding}")

---

## 2. Lists and Basic Operations

Lists are ordered, mutable collections. You can add, remove, and modify elements.

In [ ]:
# Creating a list
fruits = ["apple", "banana", "orange"]        
numbers = [1, 2, 3, 4, 5]

# Accessing elements (0-based indexing)
print(f"First fruit: {fruits[0]}")
print(f"Last fruit: {fruits[-1]}")
print(f"Second number: {numbers[1]}")  

# List length
print(f"\nNumber of fruits: {len(fruits)}")

# Adding elements
fruits.append("grape")
print(f"After adding grape: {fruits}")

# Removing elements
fruits.remove("banana")
print(f"After removing banana: {fruits}")

# List slicing
print(f"First two fruits: {fruits[0:2]}")
print(f"Last two fruits: {fruits[-2:]}")

First fruit: apple
Last fruit: orange
Second number: 2

Number of fruits: 3
After adding grape: ['apple', 'banana', 'orange', 'grape']
After removing banana: ['apple', 'orange', 'grape']
First two fruits: ['apple', 'orange']
Last two fruits: ['orange', 'grape']

In [54]:
fruits = ["apple", "banana", "orange","grape","mango","pear"] 
print(f"The last three fruit bought was {fruits[-3:]}")

The last three fruit bought was ['grape', 'mango', 'pear']

### Exercise 2.1: Shopping List
Create and manipulate a shopping list:

In [ ]:
# TODO: Create a shopping list with at least 5 items
shopping_list = []

# TODO: Print the list

# TODO: Add one more item

# TODO: Remove an item

# TODO: Print the final list

# TODO: Print the number of items

---

## 3. Dictionaries

Dictionaries store key-value pairs. They're perfect for structured data.

In [66]:
# Creating a dictionary
student = {
    "name": "Bob",
    "age": 20,
    "major": "Computer Science",
    "gpa": 3.8
}

# Accessing values
print(f"Student name: {student['name']}")
print(f"Student age: {student['age']}")

# Safe access with .get()
phone = student.get("phone", "No phone on file")
print(f"Phone: {phone}")

# Adding new key-value pairs
student["phone"] = "555-1234"
print(f"\nUpdated student: {student}")

# Getting all keys and values
print(f"\nKeys: {student.keys()}")
print(f"Values: {student.values()}")

Student name: Bob
Student age: 20
Phone: No phone on file

Updated student: {'name': 'Bob', 'age': 20, 'major': 'Computer Science', 'gpa': 3.8, 'phone': '555-1234'}

Keys: dict_keys(['name', 'age', 'major', 'gpa', 'phone'])
Values: dict_values(['Bob', 20, 'Computer Science', 3.8, '555-1234'])

In [68]:
data = {
    'Car_Brand': ['Audi', 'BMW', 'Mercedes', 'Audi', 'BMW', 'Mercedes', 'Audi', 'BMW'], # Categorical
    'Doors': [5, 6, 4, 5, 6, 4, 5, 6], # Numerical - Discrete (countable)
    'Price': [45000.50, 52000.00, 61000.75, 42000.00, 55000.25, 58000.00, 47000.50, 53000.00], # Numerical - Continuous
    'Mileage': [15000, 22000, np.nan, 18000, 25000, 30000, 12000, 21000] # Numerical with a missing value
}
df = pd.DataFrame(data)
df

  Car_Brand  Doors     Price  Mileage
0      Audi      5  45000.50  15000.0
1       BMW      6  52000.00  22000.0
2  Mercedes      4  61000.75      NaN
3      Audi      5  42000.00  18000.0
4       BMW      6  55000.25  25000.0
5  Mercedes      4  58000.00  30000.0
6      Audi      5  47000.50  12000.0
7       BMW      6  53000.00  21000.0

In [18]:
import pandas as pd


student = {
    "name": ["Bob", "Alice", "Charlie"],
    "age": [20, 22, 21],
    "major": ["Computer Science", "Mathematics", "Physics"],
    "gpa": [3.8, 3.9, 3.7]
}

df=pd.DataFrame(student)
df

      name  age             major  gpa
0      Bob   20  Computer Science  3.8
1    Alice   22       Mathematics  3.9
2  Charlie   21           Physics  3.7

### Exercise 3.1: Company Directory
Create a dictionary representing a company employee:

In [ ]:
# TODO: Create an employee dictionary with these keys:
# 
employee = {"name":["James","john"], "position":["Manager","Developer"], "department":["IT","Engineering"], "salary":[50000,60000], "years_employed":[3,2]}

# TODO: Print the employee info
#print(employee)

pf=pd.DataFrame(employee)


# TODO: Update the salary (give them a raise!)  
employee["salary"] = [55000, 65000]

# TODO: Add a new key: "email"
# TODO: Print the updated employee info

    name   position   department  salary  years_employed
0  James    Manager           IT   50000               3
1   john  Developer  Engineering   60000               2

    name   position   department  salary  years_employed
0  James    Manager           IT   50000               3
1   john  Developer  Engineering   60000               2

---

## 4. Control Flow: If/Else Statements

In [27]:
# Simple if statement
score = 95

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
else:
    grade = "F"

print(f"Score {score} = Grade {grade}")

# Comparison operators
age = 17
print(f"\nAge {age}:")
print(f"Can vote? {age >= 18}")
print(f"Can rent a car? {age >= 25}")
print(f"Is a teenager? {age >= 13 and age <= 19}")

Score 95 = Grade A

Age 17:
Can vote? False
Can rent a car? False
Is a teenager? True

In [ ]:
def

### Exercise 4.1: Grade Calculator
Create a function that assigns grades based on test scores:

In [28]:
def get_grade(score):
    """Assign a letter grade based on a numerical score."""
    # TODO: Use if/elif/else to return the appropriate grade
    # A: 90-100, B: 80-89, C: 70-79, D: 60-69, F: below 60

    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else:      
        return "F"
    pass

# Test your function
print(get_grade(95))  # Should print A
print(get_grade(85))  # Should print B
print(get_grade(75))  # Should print C
print(get_grade(65))  # Should print D
print(get_grade(55))  # Should print F

A
B
C
D
F

---

## 5. Loops

Use loops to repeat code multiple times.

In [ ]:
# For loop
print("For loop - Counting:")
for i in range(1, 7):  # Counts from 1 to 6
    print(f"Count: {i}")

# For loop with a list
print("\nFor loop - Iterating through list:")
colors = ["red", "blue", "green"]
for color in colors:    
    print(f"Color: {color}")

# For loop with enumerate
print("\nFor loop with index:")
for index, color in enumerate(colors):
    print(f"{index}: {color}")

For loop - Counting:
Count: 1
Count: 2
Count: 3
Count: 4
Count: 5
Count: 6

For loop - Iterating through list:
Color: red
Color: blue
Color: green

For loop with index:
0: red
1: blue
2: green

In [35]:
# While loop
print("While loop - Countdown:")
count = 5
while count > 0:
    print(f"Count: {count}")
    count -= 2
    
print("Blastoff!")

While loop - Countdown:
Count: 5
Count: 3
Count: 1
Blastoff!

### Exercise 5.1: Sum of Numbers
Write code to sum numbers using a loop:

In [ ]:
def sum_numbers(numbers):
    """Sum all numbers in a list using a for loop."""
    # TODO: Use a for loop to add all numbers
    
    total = 0                  #numbers=[1,2,3,4,5]-----num=1,2,3,4,5
    for num in numbers:
        total += num
    return total

# Test your function
print(sum_numbers([1, 2, 3, 4, 5]))  # Should print 15
print(sum_numbers([10, 20, 30]))      # Should print 60

15
60

---

## 6. Functions

Functions are reusable blocks of code.

In [1]:
# Basic function
def greet(name):
    """A simple greeting function."""
    return f"Hello, {name}!"

print(greet("Alice"))
print(greet("Bob"))

# Function with multiple parameters
def add(a, b):
    """Add two numbers."""
    return a + b

result = add(5, 3)
print(f"\n5 + 3 = {result}")

# Function with default parameters
def power(base, exponent=2):
    """Raise base to the power of exponent."""
    return base ** exponent

print(f"\n2^2 = {power(2)}")
print(f"2^3 = {power(2, 3)}")

Hello, Alice!
Hello, Bob!

5 + 3 = 8

2^2 = 4
2^3 = 8

### Exercise 6.1: Temperature Converter
Write functions to convert between Celsius and Fahrenheit:

In [ ]:
def celsius_to_fahrenheit(celsius):
    """Convert Celsius to Fahrenheit."""
    # TODO: Formula: F = (C × 9/5) + 32
    pass

def fahrenheit_to_celsius(fahrenheit):
    """Convert Fahrenheit to Celsius."""
    # TODO: Formula: C = (F - 32) × 5/9
    pass

# Test your functions
print(celsius_to_fahrenheit(0))   # Should print 32
print(celsius_to_fahrenheit(100)) # Should print 212
print(fahrenheit_to_celsius(32))  # Should print 0
print(fahrenheit_to_celsius(212)) # Should print 100

---

## 7. List Comprehensions (Bonus)

A concise way to create lists.

In [ ]:
# Traditional way
squares = []
for i in range(1, 6):
    squares.append(i ** 2)
print(f"Squares (traditional): {squares}")

# List comprehension way
squares = [i ** 2 for i in range(1, 6)]
print(f"Squares (comprehension): {squares}")

# With condition
even_numbers = [i for i in range(1, 11) if i % 2 == 0]
print(f"Even numbers 1-10: {even_numbers}")

### Exercise 7.1: Create Your Own
Use list comprehension to create a list of numbers squared (1-10):

In [ ]:
# TODO: Use list comprehension to create a list of squares from 1 to 10
my_squares = []

print(my_squares)

---

## Summary

Great job working through Python fundamentals! You now understand:
- ✅ Data types (int, float, str, bool, list, dict)
- ✅ Lists and basic operations
- ✅ Dictionaries and key-value access
- ✅ Control flow (if/elif/else)
- ✅ Loops (for and while)
- ✅ Functions and parameters
- ✅ List comprehensions

## Next Steps
1. Complete all exercises above
2. Review any concepts that feel shaky
3. Write 5 small programs using what you learned
4. Move on to Week 3: Data Cleaning & EDA

**Once you finish, commit your work:**
```bash
git add week-02-python/python_practice.ipynb
git commit -m "Complete Week 2: Python fundamentals"
git push
```

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns

In [5]:

# 1. DATA COLLECTION & STRUCTURE [2]
# Creating a structured DataFrame representing raw facts (Variables) [1]
data = {
    'User_ID': [3,3, 4, 5, 6, 7, 8], # Numerical - Discrete (countable) # using a dict to create a list of user IDs(combining the concept of lists and dictionaries)
    'Age': [25,25, 30, np.nan, 35, 40, 25],          # Numerical - Discrete
    'Gender': ['Male','Male', 'Female', 'Female', 'Male', 'Female', 'Male'], # Categorical - Nominal [9]
    'Quantity': [2,2, 1, 5, 3, np.nan, 2],         # Numerical - Discrete
    'Price': [20.5,20.5, 50.0, 15.0, 30.0, 25.0, 20.5] # Numerical - Continuous [10]
}

df = pd.DataFrame(data)
df

   User_ID   Age  Gender  Quantity  Price
0        3  25.0    Male       2.0   20.5
1        3  25.0    Male       2.0   20.5
2        4  30.0  Female       1.0   50.0
3        5   NaN  Female       5.0   15.0
4        6  35.0    Male       3.0   30.0
5        7  40.0  Female       NaN   25.0
6        8  25.0    Male       2.0   20.5

In [7]:
df = df.drop_duplicates()
df

   User_ID   Age  Gender  Quantity  Price
0        3  25.0    Male       2.0   20.5
2        4  30.0  Female       1.0   50.0
3        5   NaN  Female       5.0   15.0
4        6  35.0    Male       3.0   30.0
5        7  40.0  Female       NaN   25.0
6        8  25.0    Male       2.0   20.5

In [22]:
# 2. DATA PREPROCESSING (CLEANSING & TRANSFORMING) [1]
# Correcting inconsistencies: Removing duplicates [1]
#df = df.drop_duplicates()

# Replacing missing values: Using the median age as suggested in the blueprint [1]
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mode()[0])

# Encoding categorical variables: Converting "Male/Female" into numeric format [1]
df['Gender_Code'] = df['Gender'].map({'Male': 0, 'Female': 1})   # using map() which include a dictionary to convert categorical values to numeric codes

# Feature Engineering: Creating a new variable to derive deeper insights [1]
# Example: Total_Spent = Quantity x Price
df['Total_Spent'] = df['Quantity'] * df['Price']

# 3. DATA ANALYSIS (EDA) [1]
# Descriptive statistics: Calculating mean, median, and variance [1]
print("--- Statistical Summary ---")
#print(df[['Age', 'Total_Spent']].describe())

df

--- Statistical Summary ---

   User_ID   Age  Gender  Quantity  Price  Gender_Code  Total_Spent
0        3  25.0    Male       2.0   20.5            0         41.0
2        4  30.0  Female       1.0   50.0            1         50.0
3        5  30.0  Female       5.0   15.0            1         75.0
4        6  35.0    Male       3.0   30.0            0         90.0
5        7  40.0  Female       2.0   25.0            1         50.0
6        8  25.0    Male       2.0   20.5            0         41.0

In [ ]:
# 4. DATA VISUALIZATION [1]
# Representing categorical variables with a Bar Chart [9]
plt.figure(figsize=(6, 4))
sns.countplot(x='Gender', data=df)
plt.title('Distribution by Gender')
plt.show()

# Representing numerical distributions with a Histogram [10]
plt.figure(figsize=(6, 4))
sns.histplot(df['Total_Spent'], bins=5, kde=True)
plt.title('Distribution of Total Spending')
plt.show()

# Pattern Detection: Scatter plot to visualize joint variability [1, 11]
plt.figure(figsize=(6, 4))
sns.scatterplot(x='Age', y='Total_Spent', data=df)
plt.title('Age vs. Total Spending Pattern')
plt.show()

In [12]:
# 1. DATA STRUCTURE: Initializing the internship-style dataset
data ={
    'Store_ID': [101, 102, 103, None, 105],
    'Inventory_Level': [5, 3, 8, 2, 7],
    'Revenue': [15000, 8000, 22000, 5000, 18000],
    'Location': ['Urban', 'Rural', 'Urban', 'Rural', 'Suburban']
}
df = pd.DataFrame(data)

In [13]:
# 2. FUNCTIONS & PARAMETERS: For reusability in Data Cleansing [3]
# Professionals create functions to execute specific, repeatable operations.
def categorize_performance(rev, target=10000):
    """Categorizes store performance based on a revenue target."""
    # 3. CONTROL FLOW (if/elif/else): For Decision-making logic [1]
    if rev >= target * 2:
        return "High Performer"
    elif rev >= target:
        return "Meeting Target"
    else:
        return "Below Target"

# Applying the function using a parameter (target=1000)
df['Performance_Status'] = df['Revenue'].apply(categorize_performance)

In [10]:
df

   Store_ID  Inventory_Level  Revenue  Location Performance_Status
0       101                5    15000     Urban     Meeting Target
1       102                3     8000     Rural       Below Target
2       103                8    22000     Urban     High Performer
3       104                2     5000     Rural       Below Target
4       105                7    18000  Suburban     Meeting Target

In [14]:
# 4. LOOPS (for): For automated Data Processing [10]
# Useful for checking inconsistencies across multiple columns at once.
print("--- Automated Missing Value Check ---")
for column in df.columns:
    missing = df[column].isnull().sum()
    if missing > 0:
        print(f"Alert: {column} has {missing} missing values.")
    else:
        print(f"Column '{column}' is clean.")

--- Automated Missing Value Check ---
Alert: Store_ID has 1 missing values.
Column 'Inventory_Level' is clean.
Column 'Revenue' is clean.
Column 'Location' is clean.
Column 'Performance_Status' is clean.

In [15]:
# 5. LIST COMPREHENSIONS: For efficient Feature Engineering [10]
# A concise way to generate new data points or filters.
# Example: Creating a list of IDs for stores that need an 'Immediate Restock' alert.
restock_alerts = [f"Store {idx}: Restock!" for idx, inv in zip(df['Store_ID'], df['Inventory_Level']) if inv < 5]

print("\n--- Feature Engineering Insights ---")
print(f"Restock Required: {restock_alerts}")
print(df[['Store_ID', 'Revenue', 'Performance_Status']])

--- Feature Engineering Insights ---
Restock Required: ['Store 102.0: Restock!', 'Store nan: Restock!']
   Store_ID  Revenue Performance_Status
0     101.0    15000     Meeting Target
1     102.0     8000       Below Target
2     103.0    22000     High Performer
3       NaN     5000       Below Target
4     105.0    18000     Meeting Target